### ISSUE TITLE
Crash upon load

### ISSUE THREAD

**Issue by dittoslash** [PoroCYon/Ingame-Cheat-Menu#3]
TAPI.Mods+LoadException: Ingame Cheat Menu.tapi: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at TAPI.ReflectionHelper.FindSubclasses(Assembly code, Type superclass)
   at TAPI.Mod.<Load>b__0(BinBuffer bb)
   at TAPI.Mods.HandleTapiModFile(FPath path, Action`1 action)
   at TAPI.Mods.HandleModFile(FPath path, Action`1 action)
   at TAPI.Mod.Load()
   at TAPI.Mods.Load()
  at TAPI.Mods.Load()

v 1.2.4.1 tAPI r14a

**Comment by PoroCYon** [comment]
You need the full .NET 4.0 framework, and the MCT. FYI, this mod is discontinued and unsupported.
